production:
  dialect: postgres
  datasource: host=${POSTGRES_HOST} port=${POSTGRES_PORT} user=${POSTGRES_USERNAME} password=${POSTGRES_PASSWORD} sslmode=require
  dir: db/migrations
  table: __migrations

development:
  dialect: postgres
  datasource: host=${POSTGRES_HOST} port=${POSTGRES_PORT} user=${POSTGRES_USERNAME} password=${POSTGRES_PASSWORD} sslmode=require
  dir: db/migrations
  table: __migrations

local:
  dialect: postgres
  datasource: host=${POSTGRES_HOST} port=${POSTGRES_PORT} user=${POSTGRES_USERNAME} password=${POSTGRES_PASSWORD} sslmode=disable
  dir: db/migrations
  table: __migrations

local-docker:
  dialect: postgres
  datasource: dbname=postgres port=5432 sslmode=disable user=postgres password=postgres host=db
  dir: db/migrations
  table: __migrations
